### PR TITLE
Add basic version of target tracker class

### PR DESCRIPTION
**Pull request by EricPedley**
Putting this up so we have the types we want defined and a place to put the relevant code for future tasks. How I think this should work is, the new class will only be responsible for the public methods defined right now, and if we want more functionality, we just compose it with other classes.

Added two tests. One of them fails right now because is any of the labels is a 0 confidence for the ground-truth, the entire closeness score goes to zero, which we should probably change so all 0's get set to a small number instead so there's a way to break ties between matches that have one of the labels 0% matching, but that can be a future task (#18)

### CODE REVIEW

**Review by Vince-C156 — COMMENTED** [review]
Will there be multiple classes that hold shape, letter, and color confidences? A single type (or two, one for segmenetaton and another for bounding boxes) makes more sense to me. Not sure if you plan to unify everything eventually.

Does TargetTracker take in Full predictions and set them as 3D targets?

**Comment by EricPedley** [comment]
> Will there be multiple classes that hold shape, letter, and color confidences? A single type (or two, one for segmenetaton and another for bounding boxes) makes more sense to me. Not sure if you plan to unify everything eventually.
> 
> Does TargetTracker take in Full predictions and set them as 3D targets?

I could've wrapped all the class confidences into a class, then make the other ones have an instance of that wrapper instead of the confidences directly, but I felt like it was too much indirection. I think we can decide to unify everything later if we want to, and the decision doesn't really block anything.

**Comment by Vince-C156** [comment]
If i'm interpreting it correctly you mean a single Detection class similar to last year. 

I think we should think about this further for the cleanest implementation. What ever the detection class is will be involved in the "memory" based estimation between laps.

**Comment by EricPedley** [comment]
Merging rn and we can refactor the detections stuff later. I need the target tracker v1 code for adding the full sim test

**Pull request merged**
