### PR TITLE
added letter_tests.py and letter_dataset

### PR DESCRIPTION
**Pull request by scliou**

### CODE REVIEW

**Comment by EricPedley** [comment]
Good job on the test, looks good. Where did you get the dataset from? Can you include any scripts and steps used to produce it in this repo or the submodule for training code, so that we can easily reproduce it later? My goal in #16 was that we would be prepared for whenever Vince finishes the synthetic dataset using Isaac Sim, so we can just retrain all our models really easily.

**Review by EricPedley — CHANGES_REQUESTED** [review]
Good job on the test, looks good. Where did you get the dataset from? Can you include any scripts and steps used to produce it in this repo or the submodule for training code, so that we can easily reproduce it later? My goal in https://github.com/uci-uav-forge/uavf_2024/issues/16 was that we would be prepared for whenever Vince finishes the synthetic dataset using Isaac Sim, so we can just retrain all our models really easily.

So, to be more clear, the changes I'm requesting are:
1. include any scripts used to generate test data
2. document procedure to use them in a markdown file somewhere
And once we merge this, keep #16 open. We can close it once we have a script for converting a dataset of full labels into one that just has the letters, so that once we have the higher fidelity synthetic data from Isaac, we can immediately retrain the letter model.

**Comment by scliou** [comment]
I just added the script and readme for the letter data generating script in the training submodule [here](https://github.com/uci-uav-forge/imaging_training_2024/tree/main/letter_classification).  
and I also changed the script to generate dataset from the fullsize dataset as well instead of just the tile dataset

**Comment by EricPedley** [comment]
FYI, you should re-request review once you address the changes. I'm just gonna self-request this time, but in the future it's a good practice to let the reviewer know they should look at it again.

**Review by EricPedley — APPROVED** [review]
looks good

**Pull request merged**
